# Generated by Django 4.2.6 on 2023-11-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                ("graph_id", models.AutoField(primary_key=True, serialize=False)),
                ("editingEnabled", models.BooleanField(default=False)),
            ],
        ),
    ]
