# Generated by Django 4.2.6 on 2023-11-05 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("node", "0001_initial"),
        ("edge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("editing_enabled", models.BooleanField(default=False)),
                ("edges", models.ManyToManyField(blank=True, to="edge.edge")),
                ("nodes", models.ManyToManyField(blank=True, to="node.node")),
            ],
        ),
    ]
