# Generated by Django 4.2.6 on 2023-11-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="user",
            field=models.TextField(blank=True, default=123),
            preserve_default=False,
        ),
    ]
