# Generated by Django 4.2.6 on 2023-11-04 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_alter_graph_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="graph",
            old_name="editingEnabled",
            new_name="editing_enabled",
        ),
    ]
