# Generated by Django 4.2.6 on 2023-11-13 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("graph", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="node_positions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="graph",
            name="shared_user",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="graph",
            name="title",
            field=models.TextField(default="Untitled Graph"),
        ),
    ]
