# Generated by Django 4.2.6 on 2023-11-03 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("graph", "0002_alter_graph_graph_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
