# Generated by Django 4.2.6 on 2023-11-13 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("graph", "0003_graph_node_positions_graph_shared_user_graph_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="shared_user",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
