# Generated by Django 4.2.6 on 2023-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0004_remove_edge_graph"),
        ("node", "0003_remove_node_graph"),
        ("graph", "0003_graph_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="graph",
            old_name="graph_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="graph",
            name="edges",
            field=models.ManyToManyField(blank=True, to="edge.edge"),
        ),
        migrations.AddField(
            model_name="graph",
            name="nodes",
            field=models.ManyToManyField(blank=True, to="node.node"),
        ),
    ]
