# Generated by Django 4.2.6 on 2023-11-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0003_graph_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="edge_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="graph",
            name="node_ids",
            field=models.JSONField(default=list),
        ),
    ]
