# Generated by Django 4.2.6 on 2023-11-05 00:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0004_graph_edge_ids_graph_node_ids"),
        ("graph", "0004_rename_graph_id_graph_id_graph_edges_graph_nodes"),
    ]

    operations = []
