# Generated by Django 4.2.6 on 2023-11-13 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("graph", "0004_alter_graph_shared_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graph",
            name="shared_user",
            field=models.ManyToManyField(
                blank=True, related_name="shared", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
