# Generated by Django 4.2.6 on 2023-11-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0005_alter_graph_shared_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graph",
            name="shared_user",
        ),
        migrations.AddField(
            model_name="graph",
            name="shared_user",
            field=models.JSONField(default=list),
        ),
    ]
