# Generated by Django 4.2.6 on 2023-11-05 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0005_merge_20231104_1952"),
    ]

    operations = [
        migrations.RenameField(
            model_name="graph",
            old_name="editingEnabled",
            new_name="editing_enabled",
        ),
        migrations.RemoveField(
            model_name="graph",
            name="edge_ids",
        ),
        migrations.RemoveField(
            model_name="graph",
            name="node_ids",
        ),
    ]
