language: python
os: linux
# ubuntu 22.04
dist: jammy
python:
  - "3.10"

install:
  - gem install webrick
  - mkdir ./tools
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools
  - pip install -r ./backend/requirements.txt

before_script:
  - python ./backend/manage.py migrate

script:
  - black ./backend --check
  - flake8 ./backend --max-line-length=88

after_script:
  - coverage run --source=app ./backend/manage.py test
  - coverage xml
  - ./tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    region: $AWS_DEPLOY_REGION
    app: $AWS_APP_NAME
    env: $AWS_APP_ENV_PROD
    bucket_name: $AWS_BUCKET_NAME
    on:
      branch: main 
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    region: $AWS_DEPLOY_REGION
    app: $AWS_APP_NAME
    env: $AWS_APP_ENV_DEV
    bucket_name: $AWS_BUCKET_NAME
    on:
      branch: develop
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    region: $AWS_DEPLOY_REGION
    app: $AWS_APP_NAME
    env: $AWS_APP_ENV_DIRTY
    bucket_name: $AWS_BUCKET_NAME
    on:
      all_branches: true
      condition: ($TRAVIS_BRANCH =~ ^node-interface$) || (! $TRAVIS_BRANCH =~ ^(master|develop)$)