language: python

# ubuntu 22.04
os: linux
dist: jammy

python:
  - "3.10"

env:
  global:
    # keep track of current deployed version source
    - EB_DEPLOY_VERSION=travis-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER

before_install:
  # configure nodejs latest lts version
  - nvm install --lts
  - npm install -g npm@latest
  # configure coverage report tools
  - mkdir ./tools
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools
  # install deploy tools
  - npm install -g beanstalk-deploy

install:
  # install backend dependencies
  - cd ./backend
  - pip install -r requirements.txt
  - cd ..
  # install frontend dependencies
  - cd ./frontend
  - npm install
  - cd ..

before_script:
  # build frontend project
  - cd ./frontend
  - npm run build
  - cd ..
  # create backend static
  - cd ./backend
  - mkdir static
  - cd ..
  # copy frontend files to backend
  - cp -r ./frontend/build/* ./backend/static
  # backend migration
  - cd ./backend
  - python manage.py makemigrations
  - python manage.py migrate
  - cd ..

script:
  # backend lint check
  - cd ./backend
  - black . --check
  - flake8 . --max-line-length=88
  # backend coverage report
  - coverage run --source=app,user,node,edge manage.py test
  - coverage xml
  - ../tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml
  - cd ..

after_script:
  # prepare deploy zip file
  - cd ./backend
  - zip -r ../deploy.zip . -x '*.git*'
  - cd ..
  # deploy project
  - chmod +x ./deploy.sh
  - ./deploy.sh