services:
  backend:
    ports:
      - "8000:8000"
    build:
      context: ./backend
    networks:
      - internal
  frontend:
    ports:
      - "80:3000"
    build:
      context: ./frontend
    networks:
      - internal
    depends_on:
      - backend

networks:
  internal:
    driver: bridge