# Generated by Django 4.2.6 on 2023-11-05 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                ("predefined", models.BooleanField(default=False)),
                ("dependencies", models.ManyToManyField(blank=True, to="node.node")),
            ],
        ),
    ]
