# Generated by Django 4.2.6 on 2023-11-03 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0002_node_graph"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="graph",
        ),
    ]
