# Generated by Django 4.2.6 on 2023-10-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("edgeID", models.AutoField(primary_key=True, serialize=False)),
                ("belongsTo", models.IntegerField()),
                ("fromNodeID", models.IntegerField()),
                ("toNodeID", models.IntegerField()),
            ],
        ),
    ]
