# Generated by Django 4.2.6 on 2023-11-03 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edge", "0003_edge_graph"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edge",
            name="graph",
        ),
    ]
