# Generated by Django 4.2.6 on 2023-11-12 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="related_to",
            new_name="related_to_node",
        ),
    ]
