from typing import TYPE_CHECKING

from django.contrib.auth.models import AbstractUser
from django.db import models

# this makes python type hint happy
if TYPE_CHECKING:
    from graph.models import Graph


class User(AbstractUser):
    email = models.EmailField(primary_key=True)
    username = models.CharField(max_length=120)

    # created_graphs are generated by Graph model using created_by foreign key field
    created_graphs: models.Manager["Graph"]
    # shared_graphs are generated by Graph model using shared_with foreign key field
    shared_graphs = models.Manager["Graph"]
    # if user does not have an avatar, frontend will just use #001 bulbasaur
    avatar = models.CharField(max_length=120, blank=True, null=True)

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ["username"]
